<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "general.sms".
 *
 * @property int $id
 * @property int|null $status_code
 * @property int|null $phone
 * @property int|null $sms_send
 * @property string|null $create_at
 * @property string|null $end_date
 * @property int|null $status
 * @property int|null $imie
 * @property int|null $resivied_sms
 * @property string|null $sms_hash
 */
class Sms extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'sms';
    }
    public $resivied_sms;
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status'], 'default', 'value' => 0],
            [['status_code', 'phone', 'status', 'imie'], 'integer'],
            [['create_at', 'end_date'], 'safe'],
            [['sms_send'], 'string', 'max' => 32],
            [['sms_hash'], 'string', 'max' => 255],
            [['status_code'], 'exist', 'skipOnError' => true, 'targetClass' => SmsStatus::className(), 'targetAttribute' => ['status_code' => 'code']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'status_code' => Yii::t('app', 'Status Code'),
            'phone' => Yii::t('app', 'Phone'),
            'sms_send' => Yii::t('app', 'Sms Send'),
            'create_at' => Yii::t('app', 'Create At'),
            'end_date' => Yii::t('app', 'End Date'),
            'status' => Yii::t('app', 'Status'),
            'imie' => Yii::t('app', 'Imie'),
            'sms_hash' => Yii::t('app', 'Sms Hash'),
        ];
    }

    public function beforeSave($insert)
    {
        if ($this->isNewRecord) {
            $this->sms_send = rand(10000, 99999);
            $this->status = 0;
            if (substr($this->phone,0, 2) == '33'){
                $text_sms = "DTM.UZ Aktivatsiya kodingiz (Kod aktivatsii): ". $this->sms_send;
                $curl = curl_init();
                curl_setopt_array($curl, array(
                    CURLOPT_URL => 'https://notify.gov.uz/api/web/rest/send-sms',
                    CURLOPT_RETURNTRANSFER => true,
                    CURLOPT_ENCODING => '',
                    CURLOPT_MAXREDIRS => 10,
                    CURLOPT_TIMEOUT => 0,
                    CURLOPT_FOLLOWLOCATION => true,
                    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                    CURLOPT_CUSTOMREQUEST => 'POST',
                    CURLOPT_POSTFIELDS =>'{
                        "token":"mqAUPsSEfzp0xs3TTqwSsDtf",
                        "phone":998'. $this->phone. ',
                        "text":"'.$text_sms.'",
                        "provider":"uzinfocom"
                    }',
                ));
                $response = curl_exec($curl);
                curl_close($curl);
            }else{
                $code = "";
                if (substr($this->phone,0, 2) == '99' || substr($this->phone,0, 2) == '77')
                    $code = 'SMPPZG1';
                elseif (substr($this->phone,0, 2) == '93' || substr($this->phone,0, 2) == '94')
                    $code = 'SMPPUC3';
                elseif (substr($this->phone,0, 2) == '97' || substr($this->phone,0, 2) == '88')
                    $code = 'SMPPUM1';
                elseif (substr($this->phone,0, 2) == '95')
                    $code = 'SMPPZG2';
                elseif (substr($this->phone,0, 2) == '90' || substr($this->phone,0, 2) == '91')
                    $code = 'SMPPBL1';
                elseif (substr($this->phone,0, 2) == '98')
                    $code = 'SMPPERFECT';
                else{
                    return parent::beforeSave($insert); // TODO: Change the autogenerated stub
                }
                file_get_contents("http://192.168.200.115:13010/cgi-bin/sendsms?smsc=".$code."&username=habibulla&password=DTM_admin&from=5100&to=998".$this->phone."&text=DTM.UZ%20Aktivasiya%20kodingiz%20%20(Kod%20aktivatsii):%20$this->sms_send");
            }
//            $url1 = "http://192.168.200.115:13010/cgi-bin/sendsms?username=habibulla&password=DTM_admin&smsc=$code&from=5100&to=998$phone&charset=utf8&coding=2&text=Test";
           if ($this->phone != '936888499' && $this->phone != '998489900' && $this->phone != '903595413' && $this->phone != '977373389')
               file_get_contents("http://192.168.200.115:13010/cgi-bin/sendsms?smsc=$code&username=habibulla&password=DTM_admin&from=5100&to=998".$this->phone."&text=DTM.UZ%20Aktivasiya%20kodingiz%20%20(Kod%20aktivatsii):%20$this->sms_send");
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public static function create($phone, $status) {
        $one = self::find()->where(['>', 'end_date', date('Y-m-d H:i:s')])->andWhere(['status_code' => $status, 'phone' => $phone, 'status' => 0])->one();
        if (empty($one)) {
            $one = new Sms();
            $one->status_code = $status;
            $one->phone = $phone;
            $one->save();
        }
        return $one;
    }
    public function getStatusCode()
    {
        return $this->hasOne(SmsStatus::className(), ['code' => 'status_code']);
    }

    public function signup()
    {
        if (!$this->validate()) {
            return null;
        }

        $sms_model = self::findOne(['id'=>$this->id,'sms_send'=>$this->resivied_sms]);

        if (isset($sms_model) && !empty($sms_model)){
            $sms_model->status = 1;
            if($sms_model->save()){
                return true;
            }
        }

        return false;
    }
}
